### ISSUE TITLE
3_color_25lines.c的报错

### ISSUE THREAD

**Issue by chenchuhaocharlie** [RainbowRoad1/Cgame#7]
3_color_25lines.c第12行
SetConsoleCursorInfo(GetStdHandle((DWORD)-11), &(CONSOLE_CURSOR_INFO){1});报错

**Comment by RainbowRoad1** [comment]
此行代码用到了c99的特性(临时构建复合类型), 出现这种情况基本是编译器过时了, 可以尝试添加编译选项-std=c99, 最好直接换编译器...

**Comment by chenchuhaocharlie** [comment]
这么吓人的吗？抖来抖去！
[cid:image002.png@01D70791.3BA1F0C0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: RainbowRoad1<mailto:notifications@github.com>
发送时间: 2021年2月19日 9:42
收件人: RainbowRoad1/Cgame<mailto:Cgame@noreply.github.com>
抄送: Charlie Chen<mailto:chenchuhaocharlie@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [RainbowRoad1/Cgame] 3_color_25lines.c的报错 (#7)


此行代码用到了c99的特性(临时构建复合类型), 出现这种情况基本是编译器过时了, 可以尝试添加编译选项-std=c99, 最好直接换编译器...

―

**Comment by RainbowRoad1** [comment]
窗口高度不够会导致闪烁过快, 可以把H的值调小一点或者放大窗口
一般控制台窗口高度为24字符, 这里设置了25所以才会出现这种情况

**Comment by chenchuhaocharlie** [comment]
谢谢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: RainbowRoad1<mailto:notifications@github.com>
发送时间: 2021年2月20日 18:13
收件人: RainbowRoad1/Cgame<mailto:Cgame@noreply.github.com>
抄送: Charlie Chen<mailto:chenchuhaocharlie@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [RainbowRoad1/Cgame] 3_color_25lines.c的报错 (#7)


窗口高度不够会导致闪烁过快, 可以把H的值调小一点或者放大窗口
一般控制台窗口高度为24字符, 这里设置了25所以才会出现这种情况

―
